enable: "etcd"
etcd:
  rootDirectory: openim
  address: [ 101.126.80.22:2379 ]
  username: ''
  password: ''

kubernetes:
  namespace: default

rpcService:
  chat: chat-rpc-service
  admin: admin-rpc-service
  bot: bot-rpc-service
